graph LR

    
    A(OutputINCHI_PolymerLayer) --> A0>"... print unit type and subtype ..."]
    A --> A1>"fa:fa-ban ... print unit atoms ..."]
    A1 --> print_sequence_of_nums_compressing_ranges
    A --> A2>"... print crossing bonds (cap1-partner1,cap2-partner2)..."]
    A2 --> id10(OAD_Polymer_IsFirstAtomRankLower)
    A --> A3>"... print frame-shiftable pattern 'cap1,cap2-(b1a1,b1a2, b2a1,b2a2, ... )' ..."]
    A3 --> OAD_PolymerUnit_ReorderPolymerFrameShiftLinks

    OAD_PolymerUnit_ReorderPolymerFrameShiftLinks --> OAD_PolymerUnit_SetReopeningDetails
    OAD_PolymerUnit_ReorderPolymerFrameShiftLinks --> id1(OAD_PolymerUnit_ReorderLinks)

    OAD_PolymerUnit_ReorderLinks --> OAD_PolymerUnit_SortLinksAndSetSeniors

	OAD_PolymerUnit_SortLinksAndSetSeniors --> id2(OAD_PolymerUnit_SortLinks)
	OAD_PolymerUnit_SortLinksAndSetSeniors --> id11(OAD_Polymer_IsFirstAtomRankLower)

    OAD_PolymerUnit_SortLinks --> OAD_Polymer_CompareLinkSeniority
    
    OAD_Polymer_CompareLinkSeniority --> id12(OAD_Polymer_IsFirstAtomRankLower)
    OAD_Polymer_CompareLinkSeniority --> OAD_Polymer_CompareRanksOfTwoAtoms

    style id1 fill:#f9f,stroke:#333,stroke-width:4px
    style id2 fill:#f9f,stroke:#333,stroke-width:4px

    style A fill:#ECB11E,stroke:#333,stroke-width:4px