graph LR

    ProcessOneStructureEx --> P3(PreparePolymerRelatedEdits)
    ProcessOneStructureEx --> P4(PreparePolymerRelatedEdits2)
    ProcessOneStructureEx --> P5(DoPolymerRelatedEdits)
    ProcessOneStructureEx --> ProcessOneStructureExWorker

    ProcessOneStructureExWorker --> P1(OAD_ValidatePolymerAndPseudoElementData)
    P1(OAD_ValidatePolymerAndPseudoElementData) --> OAD_PolymerUnit_FindEndAtomsAndCaps
    P1(OAD_ValidatePolymerAndPseudoElementData) --> OAD_ValidateAndSortOutPseudoElementAtoms
    P1(OAD_ValidatePolymerAndPseudoElementData) --> OAD_Polymer_GetRepresentation
    ProcessOneStructureExWorker --> P2(OAD_Polymer_CyclizeCloseableUnits)
    P2(OAD_Polymer_CyclizeCloseableUnits) --> OAD_PolymerUnit_FindEndAtomsAndCaps
    P2(OAD_Polymer_CyclizeCloseableUnits) --> OAD_PolymerUnit_HasMetal
    P2(OAD_Polymer_CyclizeCloseableUnits) --> OAD_PolymerUnit_UnlinkStarsThenLinkStarPartners

    ProcessOneStructureExWorker --> ProcessOneStructure

    ProcessOneStructure --> DoOneStructureEarlyPreprocessing 
    DoOneStructureEarlyPreprocessing --> fix_odd_things
    DoOneStructureEarlyPreprocessing --> OAD_Edit_Underivatize
    DoOneStructureEarlyPreprocessing --> Ring2Chain
    ProcessOneStructure --> id6(OAD_Polymer_SmartReopenCyclizedUnits)
    subgraph Intercept and treat polymers and pseudoatoms
        id6(OAD_Polymer_SmartReopenCyclizedUnits) --> OAD_Polymer_SetAtProps
        id6(OAD_Polymer_SmartReopenCyclizedUnits) --> OAD_PolymerUnit_SetReopeningDetails
        id6(OAD_Polymer_SmartReopenCyclizedUnits) --> OAD_PolymerUnit_SortLinksAndSetSeniors    
        id6(OAD_Polymer_SmartReopenCyclizedUnits) --> OAD_PolymerUnit_ReopenCyclized
    end

    ProcessOneStructure --> OrigAtData_SaveMolfile
    ProcessOneStructure --> OrigAtData_StoreNativeInput
    ProcessOneStructure --> id4(CreateOneStructureINChI)

    ProcessOneStructure --> id5(OAD_Polymer_GetRepresentation)
    ProcessOneStructure --> id7(OAD_Polymer_CollectLinksInAllUnits)
    
    ProcessOneStructure --> TreatCreateINChIWarning
    ProcessOneStructure --> C5(SortAndPrintINChI)
    ProcessOneStructure --> DisplayOrigAndResultStructuresAndComponents
    ProcessOneStructure --> SaveOkProcessedMolfile
    ProcessOneStructure --> FreeCompAtomData
    ProcessOneStructure --> OrigStruct_Free

    subgraph Produce InChI strings
        C5(SortAndPrintINChI) --> OutputINChI2
        OutputINChI2 --> SaveEquComponentsInfoAndSortOrder
        OutputINChI2 --> C0(OutputINChI1)
        OutputINChI2 --> id10(EditINCHI_HidePolymerZz)
    end


    style id4 fill:#f9f,stroke:#333,stroke-width:4px

    style id5 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style id6 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style id6 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style id7 fill:#f6e2bd,stroke:#333,stroke-width:4px

    style C0 fill:#f9f,stroke:#333,stroke-width:4px    
    style C5 fill:#f9f,stroke:#333,stroke-width:4px    

    style id10 fill:#f6e2bd,stroke:#333,stroke-width:4px

    style P1 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style P2 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style P3 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style P4 fill:#f6e2bd,stroke:#333,stroke-width:4px
    style P5 fill:#f6e2bd,stroke:#333,stroke-width:4px
